#!/bin/sh
#
#### Information
#  Ver: 1.3 (6.05.2011)
#   By: Adrian (Sauron) Siemieniak
# Desc: Enable nessesary modules to use NTFS filesystem partition. Limited write is enabled.
####

URUKCONFIG=/etc/uruk.conf/ntfs

. /etc/uruk.d/service-common.sh

# This function should return in every status script
# 1: service is running
# 0: service is not running
service_status(){
	if [ `grep -c ntfs /proc/modules` -gt 0 ]; then
		return 1
	else
		return 0
	fi
}

case "$1" in
	start)
		service_status
		if [ $? -eq 1 ]; then
			echo "Uruk-NTFS: NTFS support already enabled."
			exit 1
		else
			echo -n "Uruk-NTFS: Enabling NTFS modules..."
			modprobe -a $ntfs_modules
			check_fail $? "Failed" "Done"
		fi
		;;
	stop)
		service_status
		if [ $? -eq 1 ]; then
			echo -n "Uruk-NTFS: Disabling NTFS rules..."
			modprobe -qar $ntfs_modules
			check_fail $? "Failed" "Done"
		else
			echo "Uruk-NTFS: NTFS support already stoped."
			exit 1
		fi
		;;
	status)
		service_status
		if [ $? -eq 1 ]; then
			echo "Uruk-NTFS: Enabled"
		else
			echo "Uruk-NTFS: Disabled"
		fi
		;;
	UIstatus)
		service_status
		if [ $? -eq 1 ]; then
			echo "on"
		else
			echo "off"
		fi
		;;
	*|"")
		echo "Uruk-Droid NTFS service"
		echo "Usage: NTFS {start|stop|status}"
		exit 1
		;;
esac

