#!/bin/sh
#
# UrukDroid service system
#
#### Information
#  Ver: 1.0 (19.01.2011)
#   By: Adrian (Sauron) Siemieniak
# Desc: Start/stop 
####

URUKCONFIG=/etc/uruk.conf/swap

if [ -f $URUKCONFIG ]; then
        . $URUKCONFIG
else
	echo "No required config file in $URUKCONFIG"
	exit 1
fi

# Check is service is enabled at all
if [ $service_enabled -ne 1 -a "$2" != "force" -a "$1" != "status" -a "$1" != "stats" ]; then
	echo "Uruk-Swap: This module is disabled in $URUKCONFIG"
        exit 1
fi

# This function should return in every status script
# 1: service is running
# 0: service is not running
service_status(){
	if [ `grep -cv /dev/block/ramzswap /proc/swaps` -gt 1 ]; then
		return 1
	else
		return 0
	fi
}

case "$1" in
	start)
		echo -n "Uruk-Swap: Enabling $size swap memory..."
		echo "Done"
		;;
	stop)
		echo -n "Uruk-Swap: Disabling swap memory..."
		echo "Done"
		;;
	status)
		service_status
		if [ $? -eq 1 ]; then
			echo "Uruk-Swap: Running"
		else
			echo "Uruk-Swap: Stoped"
		fi
		;;
	UIstatus)
		service_status
		if [ $? -eq 1 ]; then
			echo "on"
		else
			echo "off"
		fi
		;;
	*|"")
		echo "Uruk-Droid swap memory service"
		echo "Usage: swap {start|stop|status}"
		exit 1
		;;
esac

