#!/bin/sh
#
# UrukDroid service system
#
#### Information
#  Ver: 1.0 (21.02.2011)
#   By: Adrian (Sauron) Siemieniak
# Desc: VPNC service. Is a service that runs VPNC daemon to connect to your Virtual Private Network
####

URUKCONFIG=/etc/uruk.conf/vpnc

if [ -f $URUKCONFIG ]; then
        . $URUKCONFIG
else
	echo "No required config file in $URUKCONFIG"
	exit 1
fi

# Check is service is enabled at all
if [ $service_enabled -ne 1 -a "$2" != "force" ]; then
	echo "Uruk-VPNC: This module is disabled in $URUKCONFIG"
        exit 1
fi

# This function should return in every status script
# 1: service is running
# 0: service is not running
service_status(){
	if [ -f $VPNC_PID ]; then
		pid=`cat $VPNC_PID`
# Check if such a process exists for real
		if [ -d "/proc/"$pid ]; then
			return 1
                else
			rm $VPNC_PID
			return 0
		fi
	else
		return 0
	fi
}

case "$1" in
	start)
		service_status
		if [ $? -eq 1 ]; then
			echo "Uruk-VPNC: VPNC server is already running."
			exit 1
		fi
		echo -n "Uruk-VPNC: Starting VPNC service..."
		modprobe tun >/dev/null 2>&1
		mkdir /dev/net >/dev/null 2>&1
		if [ ! -L /dev/net/tun ]; then ln -s /dev/tun /dev/net/tun; fi
		/usr/local/sbin/vpnc-connect archos
		echo "Done"
		;;
	stop)
		service_status
		if [ $? -eq 1 ]; then
			echo -n "Uruk-VPNC: Disabling VPNC service..."
			PID="$(cat "$VPNC_PID" 2> /dev/null)"
			if [ -z "$PID" ]; then
				echo "no vpnc found running"
				exit 1
			fi
			if ! kill -0 "$PID" > /dev/null 2>&1; then
				echo "no vpnc found running"
				exit 1
			fi
			exec kill $PID
			echo "Done"
		else
			echo "Uruk-VPNC: Service is already stoped."
			exit 1
		fi
		;;
	status)
		service_status
		if [ $? -eq 1 ]; then
			echo "Uruk-VPNC: Running"
		else
			echo "Uruk-VPNC: Stoped"
		fi
		;;
	UIstatus)
		service_status
		if [ $? -eq 1 ]; then
			echo "on"
		else
			echo "off"
		fi
		;;
	*|"")
		echo "Uruk-Droid VPNC (Virtual Private Network 4 Cisco) service"
		echo "Usage: vpnc {start|stop|status}"
		exit 1
		;;
esac
